collections:
  questions:
    output: true
    permalink: /:title

defaults:
  - scope:
      path: ""
      path: "assets/data"
      type: "questions"
    values:
      layout: "question"
      is_question: true
  - scope:
      path: ""
    values:
      layout: "intro"
